import {
  mdiAirplane,
  mdiBabyFace,
  mdiBank,
  mdiBeer,
  mdiBicycle,
  mdiBookOpenVariant,
  mdiBriefcase,
  mdiBus,
  mdiCakeVariant,
  mdiCamera,
  mdiCar,
  mdiCash,
  mdiCellphone,
  mdiChartLine,
  mdiCoffee,
  mdiContentCut,
  mdiControllerClassic,
  mdiCreditCard,
  mdiCreation,
  mdiDotsHorizontalCircle,
  mdiDumbbell,
  mdiFerry,
  mdiFoodApple,
  mdiGasStation,
  mdiGift,
  mdiGlassCocktail,
  mdiGlassWine,
  mdiHome,
  mdiHospitalBuilding,
  mdiIceCream,
  mdiLightningBolt,
  mdiLipstick,
  mdiMedicalBag,
  mdiMovieOpen,
  mdiMusic,
  mdiPaw,
  mdiPiggyBank,
  mdiSchool,
  mdiShieldCheck,
  mdiShopping,
  mdiSilverwareForkKnife,
  mdiSofa,
  mdiStore,
  mdiSubwayVariant,
  mdiTagMultiple,
  mdiTaxi,
  mdiTrain,
  mdiTshirtCrew,
  mdiWallet,
  mdiWater,
  mdiWifi,
  mdiWrench,
} from '@mdi/js'
import {
  Apple,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  Camera,
  Car,
  ChartNoAxesCombined,
  CircleEllipsis,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  HeartPulse,
  House,
  IceCreamBowl,
  Landmark,
  Martini,
  Music2,
  PawPrint,
  PiggyBank,
  Plane,
  School,
  Scissors,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Store,
  Tag,
  TrainFront,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from '@lucide/vue'

export type CategoryIconSeries = 'outline' | 'filled'

export interface CategoryIconOption {
  key: string
  label: string
  series: CategoryIconSeries
  keywords: string
  component?: LucideIcon
  path?: string
}

type IconSeed = [key: string, label: string, keywords: string, component: LucideIcon, path: string]

const seeds: IconSeed[] = [
  ['utensils', '餐饮', '吃饭 美食 餐厅 筷子', Utensils, mdiSilverwareForkKnife],
  ['coffee', '咖啡', '饮品 奶茶 下午茶', Coffee, mdiCoffee],
  ['apple', '水果', '生鲜 苹果 蔬果', Apple, mdiFoodApple],
  ['cake', '蛋糕', '甜品 烘焙 生日', CakeSlice, mdiCakeVariant],
  ['ice-cream', '冰淇淋', '甜筒 冷饮', IceCreamBowl, mdiIceCream],
  ['beer', '啤酒', '酒吧 聚会', Beer, mdiBeer],
  ['wine', '红酒', '酒水 葡萄酒', Wine, mdiGlassWine],
  ['cocktail', '鸡尾酒', '酒吧 娱乐', Martini, mdiGlassCocktail],
  ['shopping-bag', '购物', '商场 消费 买东西', ShoppingBag, mdiShopping],
  ['shirt', '服饰', '衣服 穿搭', Shirt, mdiTshirtCrew],
  ['lipstick', '美妆', '护肤 化妆品', Sparkles, mdiLipstick],
  ['gift', '礼物', '红包 人情', Gift, mdiGift],
  ['tag', '优惠', '折扣 标签', Tag, mdiTagMultiple],
  ['bus', '公交', '公共交通 巴士', Bus, mdiBus],
  ['car', '汽车', '用车 自驾', Car, mdiCar],
  ['taxi', '打车', '出租车 网约车', Car, mdiTaxi],
  ['subway', '地铁', '轨道交通', TrainFront, mdiSubwayVariant],
  ['train', '火车', '高铁 铁路', TrainFront, mdiTrain],
  ['bike', '骑行', '单车 自行车', Bike, mdiBicycle],
  ['plane', '飞机', '航空 旅行', Plane, mdiAirplane],
  ['ship', '轮船', '航运 游轮', Ship, mdiFerry],
  ['fuel', '加油', '汽油 充电站', Fuel, mdiGasStation],
  ['house', '住房', '房租 家庭', House, mdiHome],
  ['water', '水费', '用水 水务', Droplets, mdiWater],
  ['electricity', '电费', '用电 能源', Zap, mdiLightningBolt],
  ['wifi', '网络', '宽带 流量', Wifi, mdiWifi],
  ['repair', '维修', '工具 修理', Wrench, mdiWrench],
  ['sofa', '家居', '家具 装修', Sofa, mdiSofa],
  ['phone', '手机', '话费 数码 通讯', Smartphone, mdiCellphone],
  ['book', '书籍', '阅读 图书', BookOpen, mdiBookOpenVariant],
  ['school', '教育', '学习 培训 学校', School, mdiSchool],
  ['gamepad', '游戏', '主机 手游 娱乐', Gamepad2, mdiControllerClassic],
  ['film', '影视', '电影 视频 会员', Film, mdiMovieOpen],
  ['music', '音乐', '演出 歌曲', Music2, mdiMusic],
  ['camera', '摄影', '相机 照片', Camera, mdiCamera],
  ['paw-print', '宠物', '猫 狗 萌宠', PawPrint, mdiPaw],
  ['baby', '母婴', '宝宝 儿童', Baby, mdiBabyFace],
  ['hospital', '医疗', '看病 医院 健康', HeartPulse, mdiHospitalBuilding],
  ['medicine', '药品', '买药 医药', HeartPulse, mdiMedicalBag],
  ['fitness', '健身', '运动 锻炼', Dumbbell, mdiDumbbell],
  ['wallet', '钱包', '账户 资金', Wallet, mdiWallet],
  ['banknote', '现金', '人民币 工资', Banknote, mdiCash],
  ['credit-card', '银行卡', '信用卡 支付', CreditCard, mdiCreditCard],
  ['bank', '银行', '金融 机构', Landmark, mdiBank],
  ['piggy-bank', '储蓄', '存钱 理财', PiggyBank, mdiPiggyBank],
  ['chart', '投资', '股票 基金 收益', ChartNoAxesCombined, mdiChartLine],
  ['briefcase', '工作', '办公 商务', BriefcaseBusiness, mdiBriefcase],
  ['scissors', '美容美发', '理发 剪发', Scissors, mdiContentCut],
  ['store', '商店', '门店 零售', Store, mdiStore],
  ['shield', '保险', '保障 安全', ShieldCheck, mdiShieldCheck],
  ['sparkles', '其他服务', '服务 闪光', Sparkles, mdiCreation],
  ['circle-ellipsis', '其他', '更多 未分类', CircleEllipsis, mdiDotsHorizontalCircle],
]

export const CATEGORY_ICON_OPTIONS: readonly CategoryIconOption[] = seeds.flatMap(
  ([key, label, keywords, component, path]) => [
    { key, label, keywords, series: 'outline' as const, component },
    { key: `filled:${key}`, label, keywords, series: 'filled' as const, path },
  ],
)

const iconMap = new Map(CATEGORY_ICON_OPTIONS.map((icon) => [icon.key, icon]))

export function findCategoryIcon(iconKey?: string): CategoryIconOption {
  return iconMap.get(iconKey ?? '') ?? iconMap.get('circle-ellipsis')!
}
