import type { Migration } from '../core/types'
import { INITIAL_SCHEMA_MIGRATION } from './001_initial_schema'
import { RECEIVABLES_MIGRATION } from './002_receivables'
import { PAYABLES_MIGRATION } from './003_payables'
import { IMPORT_BATCHES_MIGRATION } from './004_import_batches'
import { IMPORT_BATCHES_SOURCE_V5_MIGRATION } from './005_import_batches_source_v5'
import { TRANSACTIONS_TYPE_CONSTRAINT_V6_MIGRATION } from './006_transactions_type_constraint_v6'
import { APP_SETTINGS_V7_MIGRATION } from './007_app_settings_v7'
import { BUDGET_TEMPLATES_REMINDERS_V8_MIGRATION } from './008_budget_templates_reminders_v8'
import { USABILITY_REBUILD_V9_MIGRATION } from './009_usability_rebuild_v9'
import { TRANSACTION_DISCOUNTS_V10_MIGRATION } from './010_transaction_discounts_v10'
import { IMPORT_BATCH_ERRORS_V11_MIGRATION } from './011_import_batch_errors_v11'

export const APP_MIGRATIONS: readonly Migration[] = [
  INITIAL_SCHEMA_MIGRATION,
  RECEIVABLES_MIGRATION,
  PAYABLES_MIGRATION,
  IMPORT_BATCHES_MIGRATION,
  IMPORT_BATCHES_SOURCE_V5_MIGRATION,
  TRANSACTIONS_TYPE_CONSTRAINT_V6_MIGRATION,
  APP_SETTINGS_V7_MIGRATION,
  BUDGET_TEMPLATES_REMINDERS_V8_MIGRATION,
  USABILITY_REBUILD_V9_MIGRATION,
  TRANSACTION_DISCOUNTS_V10_MIGRATION,
  IMPORT_BATCH_ERRORS_V11_MIGRATION,
]
export const LATEST_SCHEMA_VERSION = IMPORT_BATCH_ERRORS_V11_MIGRATION.version
